# Generated by Django 3.0 on 2019-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0006_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=20, null=True, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=20, null=True, verbose_name='Отчество')),
                ('nickname', models.CharField(max_length=20, null=True, verbose_name='Творческий псевдоним')),
                ('pasport_data', models.CharField(max_length=11, null=True, verbose_name='Паспортные данные')),
                ('cost', models.PositiveIntegerField(max_length=10, verbose_name='Стоимость наима')),
                ('rider', models.TextField(null=True, verbose_name='Райдер')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.PositiveIntegerField(max_length=10, verbose_name='Стоимость аренды'),
        ),
    ]
