# Generated by Django 3.0 on 2019-12-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0007_auto_20191206_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
