# Generated by Django 3.0 on 2019-12-06 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0009_auto_20191206_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
        migrations.AddField(
            model_name='concert',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата'),
        ),
        migrations.AddField(
            model_name='concert',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость наима'),
        ),
        migrations.AlterField(
            model_name='place',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость аренды'),
        ),
    ]
