# Generated by Django 3.0 on 2019-12-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0003_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.RenameField(
            model_name='position',
            old_name='pos_name',
            new_name='name',
        ),
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='position',
            name='duties',
            field=models.TextField(null=True, verbose_name='Обязанности'),
        ),
        migrations.AddField(
            model_name='staff',
            name='pasport_data',
            field=models.TextField(null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Position', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='position',
            name='salary',
            field=models.PositiveIntegerField(verbose_name='Оклад'),
        ),
    ]
