# Generated by Django 3.0 on 2019-12-06 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0008_auto_20191206_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Artist', verbose_name='Артист')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Place', verbose_name='Площадка')),
            ],
        ),
    ]
