# Generated by Django 3.0 on 2019-12-06 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0011_auto_20191206_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Реклама'},
        ),
        migrations.RemoveField(
            model_name='ad',
            name='concert_agency_staff',
        ),
    ]
