# Generated by Django 3.0.1 on 2019-12-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0012_auto_20191206_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone_num',
            field=models.CharField(max_length=12, null=True, verbose_name='Телефон'),
        ),
    ]
