# Generated by Django 3.0.1 on 2019-12-24 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0018_concert_ticket'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'ordering': ['-artist'], 'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
    ]
