# Generated by Django 3.0.1 on 2019-12-24 20:02

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0019_auto_20191224_2245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': [django.db.models.expressions.OrderBy(django.db.models.expressions.F('nickname'), nulls_last=True)], 'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'Концерт', 'verbose_name_plural': 'Концерты'},
        ),
    ]
