# Generated by Django 3.0.1 on 2019-12-24 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0020_auto_20191224_2302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
    ]
