# Generated by Django 3.0.1 on 2019-12-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0021_auto_20191225_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='Адрес'),
        ),
    ]
