# Generated by Django 3.0 on 2019-12-06 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0010_auto_20191206_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Тип рекламы')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вид рекламы',
                'verbose_name_plural': 'Виды рекламы',
            },
        ),
        migrations.AlterField(
            model_name='artist',
            name='cost',
            field=models.PositiveIntegerField(verbose_name='Стоимость'),
        ),
        migrations.CreateModel(
            name='Ad_Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Название')),
                ('concert_agency_staff', models.ManyToManyField(to='baza_ud.Staff', verbose_name='Ответственный сотрудник концертного агенства')),
            ],
            options={
                'verbose_name': 'Рекламаное агенство',
                'verbose_name_plural': 'Рекламные агенства',
            },
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('amount', models.CharField(max_length=200, null=True, verbose_name='Количество')),
                ('ad_agency', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Ad_Agency', verbose_name='Рекламное агенство')),
                ('ad_type', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Ad_Type', verbose_name='Вид рекламы')),
                ('concert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Concert', verbose_name='Концерт')),
                ('concert_agency_staff', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='baza_ud.Staff', verbose_name='Ответственный сотрудник концертного агенства')),
            ],
        ),
    ]
