# Generated by Django 3.0.1 on 2019-12-23 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baza_ud', '0016_concert_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='image',
        ),
    ]
